config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:index, :show, :new, :edit, :create, :update, :destroy]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]

    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :messages
  validates :name, presence: true, uniqueness: true

  def show_last_message
    if (last_message = messages.last).present?
      if last_message.content?
        last_message.content
      else
        '画像が投稿されています'
      end
    else
      'まだメッセージはありません。'
    end
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :content, presence: true, unless: :image?

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # validates :name, presence: true, uniqueness: true
  has_many :group_users
  has_many :groups, through: :group_users
  
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  def index
    # ルーティングでの設定によりparamsの中にgroup_idというキーでグループのidが入るので、これを元にDBからグループを取得する
    group = Group.find(params[:group_id])
    # ajaxで送られてくる最後のメッセージのid番号を変数に代入
    last_message_id = params[:id].to_i
    # 取得したグループでのメッセージ達から、idがlast_message_idよりも新しい(大きい)メッセージ達のみを取得
    @messages = group.messages.includes(:user).where("id > ?", last_message_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    # binding.pry
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: "グループを作成しました"
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: 'グループを更新しました'
    else
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end

  def create
    # messagesコントローラーの#createアクションでメッセージを保存し、respond_toを使用してJSON形式のリクエストに対してのレスポンスを返せるように
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.json
      end
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all

    return nil if params[:keyword] == ""
    @users = User.where(['name LIKE ?', "%#{params[:keyword]}%"] ).where.not(id: current_user.id).limit(10)
    respond_to do |format|
      format.html
      format.json
    end
  end

  # データを閲覧する画面を表示するためのAction
  def show
  end
  # データを作成する画面を表示するためのAction
  def new
  @user = User.new
  end

  def edit
  end

  # データを作成するためのAction
  def create
    @user = User.new(user_params)
    @user.save
    redirect_to @user
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  # データを削除するためのAction
  def destroy
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :グループ名, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_チャットメンバーを追加"} チャットメンバーを追加
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input#user-search-field.chat-group-form__input{:placeholder => "追加したいユーザー名を入力してください", :type => "text"}/
      #user-search-result

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field--right
      #chat-group-users.js-add-user
        .chat-group-user.clearfix.js-chat-member
          %input{name: "group[user_ids][]", type: "hidden", value: current_user.id}
          %p.chat-group-user__name= current_user.name

        - group.users.each do |user|
          - if current_user.name != user.name
            .chat-group-user.clearfix.js-chat-member
              %input{name: "group[user_ids][]", type: "hidden", value: user.id}
              %p.chat-group-user__name
                = user.name 
              %a.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn
                削除

      / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
.wrapper
  = render 'messages/side_bar'

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ作成
  = render partial: 'form', locals: { group: @group }

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title Ranges
    = csrf_meta_tags
    -# CSSやJavaScriptをRailsアプリ全体に反映させる大切な記述。以下
    -# = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    -# = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = render 'layouts/notifications'
    = yield

app/views/messages/_list.html.haml
.main-header__left-box__member-list__lists
  =link_to users_path do
    =icon("far", "user")



    .main-header__left-box__member-list__lists__member
      ="2"
      -# - @group.users.each do |user|
      -#   =user.name

app/views/messages/_main_chat.html.haml
.chat-main
  .main-header
    .main-header__left-box
      .main-header__left-box__current-group
        = @group.name
      .main-header__left-box__member-list
        = render partial: 'list'
              
        .main-header__left-box__member-list__caret-down1
          =link_to "#" do
            %form{:action => "#", :method => "POST"}
              %p
                %select{:name => "type", :type => "checkbox"}
                  %option{:value => "サンプル1"} 選択してください
                  %option{:value => "ALL"}全部選択
                  %option{:value => "サンプル2"} 選択解除

                =link_to "#" do
                  %input{:type => "submit", :value => "移動"}/
              %p
        -# .main-header__left-box__member-list__caret-down2
        -#   =link_to "#" do
        -#     %input{:type => "submit", :value => "移動"}/
    .main-header__edit-btn
      =link_to "編集",edit_group_path(@group), class: "edit_btn"
  
  .messages
    = render @messages

  .form
    = form_for [@group, @message] do |f|
      .form__input
        = f.text_field :content, class: 'form__input--text', placeholder: 'メッセージを入力してください'
        .input-box
          = f.label :image, class: 'input-box__image' do
            = icon('far', 'image', class: 'icon')
            = f.file_field :image, class: 'input-box__image__file'
        = f.submit '送信', class: 'submit-btn'

app/views/messages/_message.html.haml
.message{data: {message: {id: message.id}}}
  .message__checkbox
    %label
      %input.checkbox-input{:name => "checkbox[]", :type => "checkbox", :id=>"checkboxs",}/
      %span.checkbox-parts 
    %br/
  .message__upper-info
    .message__upper-info__talker
      = message.user.name
    .message__upper-info__date
      = message.created_at.strftime("%Y年%m月%d日 %H時%M分")
  .message__text
    - if message.content.present?
      %p.message__text__content
        = message.content
    = image_tag message.image.url, class: 'message__text__image' if message.image.present?

app/views/messages/_side_bar.html.haml
.side-bar
  .side-header
    .side-header__box
      .side-header__box__user-name 
        = current_user.name
      .side-header__box__icons
        .side-header__box__icons__new-group
          = link_to new_group_path do
            = icon("far", "edit")
        .side-header__box__icons__edit-user
          = link_to edit_user_path(current_user) do
            = icon("fas", "cog")
  
  .groups
    .caption
      = "グループ一覧"
    - current_user.groups.each do |group|
      .group
        = link_to group_messages_path(group) do
          .group__group-name
            = group.name
          .group__group-message
            = group.show_last_message

app/views/messages/index.html.haml
.wrapper
  = render "side_bar"
  = render "main_chat"

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'

app/views/users/index.html.haml
-# .users-lists
-#   .users-lists__list
-#     %link(rel="stylesheet" href="users/_lists.scss")
-#     = "グループメンバー 一覧"
-#   .users-lists.clearfix.chat-member
-#     %p.users-lists-user__name= current_user.name

.users-lists
  .users-lists__list
    .users-lists__list__field.clearfix
      .users-lists__list__field--left
        %label.users-lists__list__label{:for => "chat_group_チャットメンバー"} チャットメンバー
      .users-lists__list__field--right
        #users-lists-users.js-add-user
          .users-lists-user.clearfix.js-chat-member
            %input{name: "group[user_ids][]", type: "hidden", value: current_user.id}
            %p.users-lists-user__name= current_user.name
            ="平和"